// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: internal/api/proto/transaction.proto

package dto

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransactionType int32

const (
	TransactionType_UNKNOWN    TransactionType = 0
	TransactionType_DEPOSIT    TransactionType = 1
	TransactionType_WITHDRAWAL TransactionType = 2
)

// Enum value maps for TransactionType.
var (
	TransactionType_name = map[int32]string{
		0: "UNKNOWN",
		1: "DEPOSIT",
		2: "WITHDRAWAL",
	}
	TransactionType_value = map[string]int32{
		"UNKNOWN":    0,
		"DEPOSIT":    1,
		"WITHDRAWAL": 2,
	}
)

func (x TransactionType) Enum() *TransactionType {
	p := new(TransactionType)
	*p = x
	return p
}

func (x TransactionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransactionType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_api_proto_transaction_proto_enumTypes[0].Descriptor()
}

func (TransactionType) Type() protoreflect.EnumType {
	return &file_internal_api_proto_transaction_proto_enumTypes[0]
}

func (x TransactionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransactionType.Descriptor instead.
func (TransactionType) EnumDescriptor() ([]byte, []int) {
	return file_internal_api_proto_transaction_proto_rawDescGZIP(), []int{0}
}

type UpdateBalanceReq struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Amount          float32                `protobuf:"fixed32,1,opt,name=amount,proto3" json:"amount,omitempty"`
	UserID          int32                  `protobuf:"varint,2,opt,name=userID,proto3" json:"userID,omitempty"`
	AccountID       int32                  `protobuf:"varint,3,opt,name=accountID,proto3" json:"accountID,omitempty"`
	TransactionType TransactionType        `protobuf:"varint,4,opt,name=transactionType,proto3,enum=transaction.v1.TransactionType" json:"transactionType,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateBalanceReq) Reset() {
	*x = UpdateBalanceReq{}
	mi := &file_internal_api_proto_transaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBalanceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBalanceReq) ProtoMessage() {}

func (x *UpdateBalanceReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_proto_transaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBalanceReq.ProtoReflect.Descriptor instead.
func (*UpdateBalanceReq) Descriptor() ([]byte, []int) {
	return file_internal_api_proto_transaction_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateBalanceReq) GetAmount() float32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *UpdateBalanceReq) GetUserID() int32 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *UpdateBalanceReq) GetAccountID() int32 {
	if x != nil {
		return x.AccountID
	}
	return 0
}

func (x *UpdateBalanceReq) GetTransactionType() TransactionType {
	if x != nil {
		return x.TransactionType
	}
	return TransactionType_UNKNOWN
}

type UpdateBalanceRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	NewBalance    float32                `protobuf:"fixed32,3,opt,name=newBalance,proto3" json:"newBalance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBalanceRes) Reset() {
	*x = UpdateBalanceRes{}
	mi := &file_internal_api_proto_transaction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBalanceRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBalanceRes) ProtoMessage() {}

func (x *UpdateBalanceRes) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_proto_transaction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBalanceRes.ProtoReflect.Descriptor instead.
func (*UpdateBalanceRes) Descriptor() ([]byte, []int) {
	return file_internal_api_proto_transaction_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateBalanceRes) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UpdateBalanceRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateBalanceRes) GetNewBalance() float32 {
	if x != nil {
		return x.NewBalance
	}
	return 0
}

// common models
type ErrorMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          uint32                 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorMessage) Reset() {
	*x = ErrorMessage{}
	mi := &file_internal_api_proto_transaction_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorMessage) ProtoMessage() {}

func (x *ErrorMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_proto_transaction_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorMessage.ProtoReflect.Descriptor instead.
func (*ErrorMessage) Descriptor() ([]byte, []int) {
	return file_internal_api_proto_transaction_proto_rawDescGZIP(), []int{2}
}

func (x *ErrorMessage) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ErrorMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_internal_api_proto_transaction_proto protoreflect.FileDescriptor

const file_internal_api_proto_transaction_proto_rawDesc = "" +
	"\n" +
	"$internal/api/proto/transaction.proto\x12\x0etransaction.v1\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\xab\x01\n" +
	"\x10UpdateBalanceReq\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x02R\x06amount\x12\x16\n" +
	"\x06userID\x18\x02 \x01(\x05R\x06userID\x12\x1c\n" +
	"\taccountID\x18\x03 \x01(\x05R\taccountID\x12I\n" +
	"\x0ftransactionType\x18\x04 \x01(\x0e2\x1f.transaction.v1.TransactionTypeR\x0ftransactionType\"`\n" +
	"\x10UpdateBalanceRes\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1e\n" +
	"\n" +
	"newBalance\x18\x03 \x01(\x02R\n" +
	"newBalance\"<\n" +
	"\fErrorMessage\x12\x12\n" +
	"\x04code\x18\x01 \x01(\rR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*;\n" +
	"\x0fTransactionType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aDEPOSIT\x10\x01\x12\x0e\n" +
	"\n" +
	"WITHDRAWAL\x10\x022\xa8\x02\n" +
	"\x0eBalanceService\x12\x95\x02\n" +
	"\rUpdateBalance\x12 .transaction.v1.UpdateBalanceReq\x1a .transaction.v1.UpdateBalanceRes\"\xbf\x01\x92A\xa1\x01\n" +
	"\x1eTransaction Account Management\x12\x16Update Account BalanceJ6\n" +
	"\x03400\x12/\n" +
	"\vBad Request\x12 \n" +
	"\x1e\x1a\x1c.transaction.v1.ErrorMessager/\n" +
	"-\n" +
	"\tX-API-Key\x12\x1cAPI Key For Using Backoffice\x18\x01(\x01\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/balance/updateB?\x92A!\x12\x1c\n" +
	"\x13Banking Transaction2\x053.0.0*\x01\x01Z\x19internal/api/grpc/dto;dtob\x06proto3"

var (
	file_internal_api_proto_transaction_proto_rawDescOnce sync.Once
	file_internal_api_proto_transaction_proto_rawDescData []byte
)

func file_internal_api_proto_transaction_proto_rawDescGZIP() []byte {
	file_internal_api_proto_transaction_proto_rawDescOnce.Do(func() {
		file_internal_api_proto_transaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_api_proto_transaction_proto_rawDesc), len(file_internal_api_proto_transaction_proto_rawDesc)))
	})
	return file_internal_api_proto_transaction_proto_rawDescData
}

var file_internal_api_proto_transaction_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_api_proto_transaction_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_internal_api_proto_transaction_proto_goTypes = []any{
	(TransactionType)(0),     // 0: transaction.v1.TransactionType
	(*UpdateBalanceReq)(nil), // 1: transaction.v1.UpdateBalanceReq
	(*UpdateBalanceRes)(nil), // 2: transaction.v1.UpdateBalanceRes
	(*ErrorMessage)(nil),     // 3: transaction.v1.ErrorMessage
}
var file_internal_api_proto_transaction_proto_depIdxs = []int32{
	0, // 0: transaction.v1.UpdateBalanceReq.transactionType:type_name -> transaction.v1.TransactionType
	1, // 1: transaction.v1.BalanceService.UpdateBalance:input_type -> transaction.v1.UpdateBalanceReq
	2, // 2: transaction.v1.BalanceService.UpdateBalance:output_type -> transaction.v1.UpdateBalanceRes
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_api_proto_transaction_proto_init() }
func file_internal_api_proto_transaction_proto_init() {
	if File_internal_api_proto_transaction_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_api_proto_transaction_proto_rawDesc), len(file_internal_api_proto_transaction_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_api_proto_transaction_proto_goTypes,
		DependencyIndexes: file_internal_api_proto_transaction_proto_depIdxs,
		EnumInfos:         file_internal_api_proto_transaction_proto_enumTypes,
		MessageInfos:      file_internal_api_proto_transaction_proto_msgTypes,
	}.Build()
	File_internal_api_proto_transaction_proto = out.File
	file_internal_api_proto_transaction_proto_goTypes = nil
	file_internal_api_proto_transaction_proto_depIdxs = nil
}
