apiVersion: v1
kind: Service
metadata:
  name: backoffice-clusterip
spec:
  type: ClusterIP
  selector:
    app: backoffice
  ports:
    - port: {{ .Values.backoffice.port }}
      targetPort: {{ .Values.backoffice.port }}
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: backoffice-nodeport
# spec:
#   type: NodePort
#   selector:
#     app: backoffice
#   ports:
#     - port: {{ .Values.backoffice.port }}
#       targetPort: {{ .Values.backoffice.port }}
#       nodePort: {{ .Values.backoffice.nodePort }}