apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nats
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nats
  serviceName: nats
  template:
    metadata:
      labels:
        app: nats
    spec:
      containers:
        - name: nats
          image: nats:2.10
          ports:
            - containerPort: 4222
          args:
            - "--jetstream"
          volumeMounts:
            - name: nats-data
              mountPath: /data
      volumes:
        - name: nats-data
          persistentVolumeClaim:
            claimName: nats-data