apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {
        worker_connections 1024;
    }

    http {
        sendfile on;
        tcp_nopush on;
        tcp_nodelay on;
        keepalive_timeout 65;
        
        include /etc/nginx/mime.types;
        default_type application/octet-stream;

        server {
            listen 80;
            server_name _;

            location /transaction/ {
                proxy_pass http://transaction-clusterip:80/;
                
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }

            location = /transaction {
                return 301 $scheme://$host$uri/;
            }

            # Strip /backoffice prefix when forwarding
            location /backoffice/ {
                proxy_pass http://backoffice-clusterip:80/;
                
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }

            # Handle /backoffice without trailing slash
            location = /backoffice {
                return 301 $scheme://$host$uri/;
            }

            # Default handler
            location / {
                return 404;
            }
        }
    }

