apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transaction
  template:
    metadata:
      labels:
        app: transaction
    spec:
      containers:
        - name: transaction
          image: {{ .Values.transaction.image }}
          ports:
            - containerPort: {{ .Values.transaction.port }}
          envFrom:
            - configMapRef:
                name: transaction-config