apiVersion: v1
kind: ConfigMap
metadata:
  name: transaction-config
data:
  TRANSACTION_GRPC_GATEWAY_PORT: "{{ .Values.transaction.grpc.gateway.port }}"
  TRANSACTION_GRPC_GATEWAY_IP: "{{ .Values.transaction.grpc.gateway.host }}"
  TRANSACTION_GRPC_GATEWAY_API_KEY: "{{ .Values.transaction.grpc.gateway.apiKey }}"
  TRANSACTION_CRDB_HOST: "{{ .Values.transaction.crdb.host }}"
  TRANSACTION_NATS_URL: "{{ .Values.transaction.nats.url }}"
