apiVersion: v1
kind: Service
metadata:
  name: transaction-clusterip
spec:
  type: ClusterIP
  selector:
    app: transaction
  ports:
    - port: {{ .Values.transaction.service.port }}
      targetPort: {{ .Values.transaction.service.port }}
