// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: internal/api/proto/user.proto

package dto

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserReq) Reset() {
	*x = CreateUserReq{}
	mi := &file_internal_api_proto_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserReq) ProtoMessage() {}

func (x *CreateUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_proto_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserReq.ProtoReflect.Descriptor instead.
func (*CreateUserReq) Descriptor() ([]byte, []int) {
	return file_internal_api_proto_user_proto_rawDescGZIP(), []int{0}
}

func (x *CreateUserReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateUserReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type CreateUserRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	UserID        string                 `protobuf:"bytes,3,opt,name=userID,proto3" json:"userID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRes) Reset() {
	*x = CreateUserRes{}
	mi := &file_internal_api_proto_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRes) ProtoMessage() {}

func (x *CreateUserRes) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_proto_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRes.ProtoReflect.Descriptor instead.
func (*CreateUserRes) Descriptor() ([]byte, []int) {
	return file_internal_api_proto_user_proto_rawDescGZIP(), []int{1}
}

func (x *CreateUserRes) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CreateUserRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateUserRes) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

type CreateAccountReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        string                 `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccountReq) Reset() {
	*x = CreateAccountReq{}
	mi := &file_internal_api_proto_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountReq) ProtoMessage() {}

func (x *CreateAccountReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_proto_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountReq.ProtoReflect.Descriptor instead.
func (*CreateAccountReq) Descriptor() ([]byte, []int) {
	return file_internal_api_proto_user_proto_rawDescGZIP(), []int{2}
}

func (x *CreateAccountReq) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

type CreateAccountRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	AccountID     int32                  `protobuf:"varint,3,opt,name=accountID,proto3" json:"accountID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccountRes) Reset() {
	*x = CreateAccountRes{}
	mi := &file_internal_api_proto_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountRes) ProtoMessage() {}

func (x *CreateAccountRes) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_proto_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountRes.ProtoReflect.Descriptor instead.
func (*CreateAccountRes) Descriptor() ([]byte, []int) {
	return file_internal_api_proto_user_proto_rawDescGZIP(), []int{3}
}

func (x *CreateAccountRes) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CreateAccountRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateAccountRes) GetAccountID() int32 {
	if x != nil {
		return x.AccountID
	}
	return 0
}

// common models
type ErrorMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          uint32                 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorMessage) Reset() {
	*x = ErrorMessage{}
	mi := &file_internal_api_proto_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorMessage) ProtoMessage() {}

func (x *ErrorMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_proto_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorMessage.ProtoReflect.Descriptor instead.
func (*ErrorMessage) Descriptor() ([]byte, []int) {
	return file_internal_api_proto_user_proto_rawDescGZIP(), []int{4}
}

func (x *ErrorMessage) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ErrorMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_internal_api_proto_user_proto protoreflect.FileDescriptor

const file_internal_api_proto_user_proto_rawDesc = "" +
	"\n" +
	"\x1dinternal/api/proto/user.proto\x12\rbackoffice.v1\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"9\n" +
	"\rCreateUserReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\"U\n" +
	"\rCreateUserRes\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x16\n" +
	"\x06userID\x18\x03 \x01(\tR\x06userID\"*\n" +
	"\x10CreateAccountReq\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\tR\x06userID\"^\n" +
	"\x10CreateAccountRes\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1c\n" +
	"\taccountID\x18\x03 \x01(\x05R\taccountID\"<\n" +
	"\fErrorMessage\x12\x12\n" +
	"\x04code\x18\x01 \x01(\rR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\x9b\x04\n" +
	"\vUserService\x12\xfb\x01\n" +
	"\n" +
	"CreateUser\x12\x1c.backoffice.v1.CreateUserReq\x1a\x1c.backoffice.v1.CreateUserRes\"\xb0\x01\x92A\x95\x01\n" +
	"\x1aBackoffice User Management\x12\x0fCreate New UserJ5\n" +
	"\x03400\x12.\n" +
	"\vBad Request\x12\x1f\n" +
	"\x1d\x1a\x1b.backoffice.v1.ErrorMessager/\n" +
	"-\n" +
	"\tX-API-Key\x12\x1cAPI Key For Using Backoffice\x18\x01(\x01\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/user/create\x12\x8d\x02\n" +
	"\rCreateAccount\x12\x1f.backoffice.v1.CreateAccountReq\x1a\x1f.backoffice.v1.CreateAccountRes\"\xb9\x01\x92A\x9b\x01\n" +
	"\x1dBackoffice Account Management\x12\x12Create New AccountJ5\n" +
	"\x03400\x12.\n" +
	"\vBad Request\x12\x1f\n" +
	"\x1d\x1a\x1b.backoffice.v1.ErrorMessager/\n" +
	"-\n" +
	"\tX-API-Key\x12\x1cAPI Key For Using Backoffice\x18\x01(\x01\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/account/createB>\x92A \x12\x1b\n" +
	"\x12Banking Backoffice2\x053.0.0*\x01\x01Z\x19internal/api/grpc/dto;dtob\x06proto3"

var (
	file_internal_api_proto_user_proto_rawDescOnce sync.Once
	file_internal_api_proto_user_proto_rawDescData []byte
)

func file_internal_api_proto_user_proto_rawDescGZIP() []byte {
	file_internal_api_proto_user_proto_rawDescOnce.Do(func() {
		file_internal_api_proto_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_api_proto_user_proto_rawDesc), len(file_internal_api_proto_user_proto_rawDesc)))
	})
	return file_internal_api_proto_user_proto_rawDescData
}

var file_internal_api_proto_user_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_internal_api_proto_user_proto_goTypes = []any{
	(*CreateUserReq)(nil),    // 0: backoffice.v1.CreateUserReq
	(*CreateUserRes)(nil),    // 1: backoffice.v1.CreateUserRes
	(*CreateAccountReq)(nil), // 2: backoffice.v1.CreateAccountReq
	(*CreateAccountRes)(nil), // 3: backoffice.v1.CreateAccountRes
	(*ErrorMessage)(nil),     // 4: backoffice.v1.ErrorMessage
}
var file_internal_api_proto_user_proto_depIdxs = []int32{
	0, // 0: backoffice.v1.UserService.CreateUser:input_type -> backoffice.v1.CreateUserReq
	2, // 1: backoffice.v1.UserService.CreateAccount:input_type -> backoffice.v1.CreateAccountReq
	1, // 2: backoffice.v1.UserService.CreateUser:output_type -> backoffice.v1.CreateUserRes
	3, // 3: backoffice.v1.UserService.CreateAccount:output_type -> backoffice.v1.CreateAccountRes
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_api_proto_user_proto_init() }
func file_internal_api_proto_user_proto_init() {
	if File_internal_api_proto_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_api_proto_user_proto_rawDesc), len(file_internal_api_proto_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_api_proto_user_proto_goTypes,
		DependencyIndexes: file_internal_api_proto_user_proto_depIdxs,
		MessageInfos:      file_internal_api_proto_user_proto_msgTypes,
	}.Build()
	File_internal_api_proto_user_proto = out.File
	file_internal_api_proto_user_proto_goTypes = nil
	file_internal_api_proto_user_proto_depIdxs = nil
}
